# -*- coding: utf-8 -*-
"""music_instrument_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w1AvPLzMSUp8JUIKr2CbFgnYUpAlhIzB

# Imports
"""

import os
import time
import psutil
import librosa
import queue
import threading
import numpy as np
import pandas as pd
import librosa.display
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from concurrent.futures import ThreadPoolExecutor

from google.colab import drive
drive.mount('/content/drive')

"""# Configuration"""

# Config
DATASET_PATH = "/content/drive/MyDrive/Colab Notebooks/music/Train"
SAMPLE_RATE = 22050
DURATION = 5
SAMPLES_PER_TRACK = SAMPLE_RATE * DURATION

"""# Extract Mel-spectogram from audio"""

# Function to extract Mel-spectrogram from audio
def extract_mel_spectrogram(file_path, sr=22050, duration=5, max_len=216):
    y, sr = librosa.load(file_path, sr=sr, duration=duration)
    mel = librosa.feature.melspectrogram(y=y, sr=sr, n_mels=128)
    mel_db = librosa.power_to_db(mel, ref=np.max)
    if mel_db.shape[1] < max_len:
        pad_width = max_len - mel_db.shape[1]
        mel_db = np.pad(mel_db, pad_width=((0, 0), (0, pad_width)), mode='constant')
    else:
        mel_db = mel_db[:, :max_len]
    return mel_db

"""# Prepare data

*   collect all audio file paths and labels
*   Process files using ThreadPoolExecutor
*   Preprocess data
*   Train/Test split

# Thread Pool Executor
"""

start_time = time.time()
process = psutil.Process(os.getpid())
start_mem = process.memory_info().rss / 1024 / 1024
# ThreadPool-based processing function
def process_file_thread(file_path, label):
    try:
        mel = extract_mel_spectrogram(file_path)
        return mel, label
    except Exception as e:
        print(f"Error: {file_path}, {e}")
        return None

# Collect all audio file paths and labels
tasks = []
for label in os.listdir(DATASET_PATH):
    folder = os.path.join(DATASET_PATH, label)
    if not os.path.isdir(folder):
        continue
    for file_name in os.listdir(folder):
        if file_name.endswith(".mp3") or file_name.endswith(".wav"):
            file_path = os.path.join(folder, file_name)
            tasks.append((file_path, label))

def monitor_threads():
    # Print the number of active threads
    print(f"Active threads: {threading.active_count()}")

# Process files using ThreadPoolExecutor
with ThreadPoolExecutor(max_workers=4) as executor:
    results = list(executor.map(lambda args: process_file_thread(*args), tasks))
    monitor_threads()

# Filter out None results
features = [res[0] for res in results if res is not None]
labels = [res[1] for res in results if res is not None]

# Preprocess data
X = np.array(features)[..., np.newaxis]  # Add channel dimension
y = to_categorical(LabelEncoder().fit_transform(labels))

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

end_mem = process.memory_info().rss / 1024 / 1024
end_time = time.time()
print(f"Memory Used: {end_mem - start_mem:.2f} MB")
print(f"Time Taken: {end_time - start_time:.2f} seconds")

"""# Multithreading"""

start_time = time.time()
process = psutil.Process(os.getpid())
start_mem = process.memory_info().rss / 1024 / 1024

# Collect all audio file paths and labels
tasks = []
for label in os.listdir(DATASET_PATH):
    folder = os.path.join(DATASET_PATH, label)
    if not os.path.isdir(folder):
        continue
    for file_name in os.listdir(folder):
        if file_name.endswith(".mp3") or file_name.endswith(".wav"):
            file_path = os.path.join(folder, file_name)
            tasks.append((file_path, label))

# Create a thread-safe queue to store results
results_queue = queue.Queue()

# Worker function for threads
def thread_worker(file_path, label):
    try:
        mel = extract_mel_spectrogram(file_path)
        results_queue.put((mel, label))
    except Exception as e:
        print(f"Error processing {file_path}: {e}")

# Create and start threads
threads = []
for file_path, label in tasks:
    thread = threading.Thread(target=thread_worker, args=(file_path, label))
    thread.start()
    threads.append(thread)

# Wait for all threads to finish
for thread in threads:
    thread.join()

# Collect results
results = list(results_queue.queue)

# Filter out None results
features = [res[0] for res in results if res is not None]
labels = [res[1] for res in results if res is not None]

# Preprocess data
X = np.array(features)[..., np.newaxis]  # Add channel dimension
y = to_categorical(LabelEncoder().fit_transform(labels))

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

end_mem = process.memory_info().rss / 1024 / 1024
end_time = time.time()
print(f"Memory Used: {end_mem - start_mem:.2f} MB")
print(f"Time Taken: {end_time - start_time:.2f} seconds")

"""# Dataframe"""

df = pd.DataFrame(tasks, columns=["file_path", "label"])
df.head()

df.tail()

"""# Data after extract mel-spectogram"""

# List to store flattened Mel-spectrograms and their labels
mel_db_list = [] #Store Mel-spectrograms (flattened)
labels = [] #Store corresponding labels

# Loop through dataset and extract Mel-spectrograms
for label in os. listdir(DATASET_PATH):
  folder = os.path. join(DATASET_PATH, label)
  if not os. path. isdir(folder):
    continue
  for file_name in os. listdir(folder):
    if file_name.endswith(".mp3") or file_name.endswith(".wav"):
      file_path = os. path. join (folder, file_name)
      try:
          mel_db = extract_mel_spectrogram (file_path)
          mel_db_flat = mel_db.flatten() # Flatten the Mel-spectrogram to a 1D array
          mel_db_list.append (mel_db_flat) # Add flattened Mel-spectrogram to list
          labels. append (label) # Add label to list
      except Exception as e:
          print(f"Error processing (file_path): {e}")

# Convert list of Mel-spectrograms to a pandas DataFrame
mel_db_df = pd. DataFrame(mel_db_list)

# Add a column for the labels
mel_db_df ['Label'] = labels

# Display the first few rows of the table
print (mel_db_df. head ())

# Optionally, save the DataFrame to a CSV file
mel_db_df.to_csv('mel_spectrograms_table.csv', index=False)

"""# Define and Train model"""

# Define CNN model
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=X_train.shape[1:]),
    MaxPooling2D((2, 2)),
    Dropout(0.3),

    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Dropout(0.3),

    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Dropout(0.3),

    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.3),
    Dense(y.shape[1], activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(X_train, y_train, epochs=20, batch_size=32, validation_data=(X_test, y_test))

"""# Predict Instrument"""

# Predict instrument for new audio
def predict_instrument(file_path, model, label_encoder):
    mel = extract_mel_spectrogram(file_path)
    mel = mel[np.newaxis, ..., np.newaxis]
    prediction = model.predict(mel)
    predicted_label = label_encoder.inverse_transform(np.argmax(prediction, axis=1))[0]
    return predicted_label

# Show prediction
new_audio_path = "/content/drive/MyDrive/Colab Notebooks/music/Test_submission/Sad-Violin-Slow-K-www.fesliyanstudios.com.wav"
label_encoder = LabelEncoder()
label_encoder.fit(labels)
predicted = predict_instrument(new_audio_path, model, label_encoder)
print(f"Predicted Instrument: {predicted}")

plt.figure(figsize=(10, 4))
librosa.display.specshow(X[0].squeeze(), x_axis='time', y_axis='mel', sr=SAMPLE_RATE)
plt.colorbar(format='%+2.0f dB')
plt.title('Mel Spectrogram')
plt.tight_layout()
plt.show()

print("Shape of X:", X.shape)
print("Labels:", set(labels))

"""# Waveform"""

# Load audio file
y, sr = librosa.load('/content/drive/MyDrive/Colab Notebooks/music/Test_submission/Sad-Violin-Slow-K-www.fesliyanstudios.com.wav', sr=None)  # y = waveform, sr = sampling rate

plt.figure(figsize=(10, 3))
librosa.display.waveshow(y, sr=sr)
plt.title(" Violin Waveform")
plt.xlabel("Time (s)")
plt.ylabel("Amplitude")
plt.show()

# Load audio file
y, sr = librosa.load('/content/drive/MyDrive/Colab Notebooks/music/Test_submission/ROOM_room6_MUS_pachelbel_DEV_amazon.wav', sr=None)  # y = waveform, sr = sampling rate

plt.figure(figsize=(10, 3))
librosa.display.waveshow(y, sr=sr)
plt.title("Piano Waveform")
plt.xlabel("Time (s)")
plt.ylabel("Amplitude")
plt.show()

# Load audio file
y, sr = librosa.load('/content/drive/MyDrive/Colab Notebooks/music/Test_submission/acoustic-guitar-logo-13084.wav', sr=None)  # y = waveform, sr = sampling rate

plt.figure(figsize=(10, 3))
librosa.display.waveshow(y, sr=sr)
plt.title("Guitar Waveform")
plt.xlabel("Time (s)")
plt.ylabel("Amplitude")
plt.show()

# Load audio file
y, sr = librosa.load('/content/drive/MyDrive/Colab Notebooks/music/Test_submission/rock-drum-loop-85371.wav', sr=None)  # y = waveform, sr = sampling rate

plt.figure(figsize=(10, 3))
librosa.display.waveshow(y, sr=sr)
plt.title("Drum Waveform")
plt.xlabel("Time (s)")
plt.ylabel("Amplitude")
plt.show()